### ISSUE TITLE
Plugin not compatible with latest dokuwiki Hogfather

### ISSUE THREAD

**Issue by masterzen** [tstaerk/mediasyntax#27]
Hi,

Unfortunately when installing this plugin in the latest dokuwiki Hogfather version, all pages ends with the following PHP error:

```
[05-Sep-2020 06:18:12 America/Chicago] PHP Fatal error:  Uncaught Error: Class 'Doku_Handler_List' not found in /var/www/wiki/lib/plugins/mediasyntax/syntax/listblock.php:88
Stack trace:
#0 /var/www/wiki/inc/load.php(147): require()
#1 [internal function]: load_autoload('syntax_plugin_m...')
#2 [internal function]: spl_autoload_call('syntax_plugin_m...')
#3 /var/www/wiki/inc/Extension/PluginController.php(103): class_exists('syntax_plugin_m...', true)
#4 /var/www/wiki/inc/pluginutils.php(54): dokuwiki\Extension\PluginController->load('syntax', 'mediasyntax_lis...', false, false)
#5 /var/www/wiki/inc/parserutils.php(559): plugin_load('syntax', 'mediasyntax_lis...')
#6 /var/www/wiki/inc/parserutils.php(204): p_get_parsermodes()
#7 /var/www/wiki/inc/parserutils.php(181): p_get_instructions('Welcome to the ...')
#8 /var/www/wiki/inc/parserutils.php(501): p_cached_instructions('/home1/ogeefion...', false, 'start')
#9 /var/www/wiki/inc/parserutils.php(282): p_render_metadata('start', Array)
#10 /home1/ogeefio in /var/www/wiki/lib/plugins/mediasyntax/syntax/listblock.php on line 88
```

Indeed the `Doku_Handler_List` class doesn't exist anymore in the Dokuwiki code base.

**Comment by tstaerk** [comment]
Hi,

sorry I cannot completely rewrite the plugin right now. Do you have any proposals how to make it work again?

thanks
 
Thorsten
